server:
  port: 8080
  servlet:
    context-patch: /bootcamp


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://wmqrvnvviywixh:d2f5fd76ca1d0c5f56b895183b4910e9083da9b67d15b0bc6739aaa8b7712a51@ec2-35-169-188-58.compute-1.amazonaws.com:5432/d8su9f41sachqv

    username: wmqrvnvviywixh
    password: d2f5fd76ca1d0c5f56b895183b4910e9083da9b67d15b0bc6739aaa8b7712a51
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para a Semana Dev Week Santander
